=== OlehKakherskiy/EpamCourseTasks/Project3/src/medicine.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">

    <xs:element name="medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicine" type="medicine" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="medicine">
        <xs:sequence>
            <xs:element name="pharm" type="notEmptyString"/>
            <xs:element name="group" type="medicineGroup"/>
            <xs:element name="analogues" type="analogue" minOccurs="0"/>
            <xs:element name="versions" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="version" type="version" minOccurs="1"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="notEmptyString" use="required"/>
        <xs:attribute name="ID" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:simpleType name="medicineGroup">
        <xs:restriction base="xs:string">
            <xs:enumeration value="antibiotics"/>
            <xs:enumeration value="vitamins"/>
            <xs:enumeration value="antiviral"/>
            <xs:enumeration value="antiinflammatory"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="analogue">
        <xs:sequence>
            <xs:element name="analogueID" type="xs:IDREF" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="version">
        <xs:all>
            <xs:element name="producers" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="producer" minOccurs="1" type="manufacturer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="dosages" minOccurs="1">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="dosage" type="dosage"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="manufacturer">
        <xs:sequence>
            <xs:element name="certificate" type="certificate" minOccurs="1" maxOccurs="1"/>
            <xs:element name="packages" minOccurs="1" >
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="package" type="package"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="certificate">
        <xs:all>
            <xs:element name="startDate" type="xs:date" minOccurs="1"/>
            <xs:element name="endDate" type="xs:date" minOccurs="1"/>
            <xs:element name="registeringOrganisation" type="notEmptyString" minOccurs="1"/>
        </xs:all>
        <xs:attribute name="certificateID" use="required" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="package">
        <xs:attribute name="count" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="measureUnit" type="measureUnit" use="optional" default="gram"/>
        <xs:attribute name="price" use="required" type="xs:positiveInteger"/>
        <xs:attribute name="packType" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="packType1"/>
                    <xs:enumeration value="packType2"/>
                    <xs:enumeration value="packType3"/>
                    <xs:enumeration value="packType4"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="representationType" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="drops"/>
                    <xs:enumeration value="pills"/>
                    <xs:enumeration value="capsules"/>
                    <xs:enumeration value="powder"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dosage">
        <xs:attribute name="dosageCount" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="times" type="xs:positiveInteger" use="optional" default="1"/>
        <xs:attribute name="per" type="dosagePeriod" use="required"/>
        <xs:attribute name="for" type="peopleGroup" use="required"/>
        <xs:attribute name="measureUnit" type="measureUnit" use="required"/>
    </xs:complexType>

    <xs:simpleType name="dosagePeriod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="30m"/>
            <xs:enumeration value="hour"/>
            <xs:enumeration value="day"/>
            <xs:enumeration value="week"/>
            <xs:enumeration value="month"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="peopleGroup">
        <xs:restriction base="xs:string">
            <xs:enumeration value="adult"/>
            <xs:enumeration value="adult men"/>
            <xs:enumeration value="adult women"/>
            <xs:enumeration value="children"/>
            <xs:enumeration value="pregnant"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="measureUnit">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gram"/>
            <xs:enumeration value="milliliter"/>
            <xs:enumeration value="thing"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== OlehKakherskiy/EpamCourseTasks/Project3/src/file.xml
<?xml version="1.0" encoding="UTF-8" ?>

<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="medicine.xsd">
    <medicine name="name1" ID="ae2">
        <pharm>s</pharm>
        <group>antibiotics</group>
        <versions>
            <certificate certificateID="certID1">
                <startDate>1995-05-11</startDate>
                <endDate>2016-11-11</endDate>
                <registeringOrganisation>organization1</registeringOrganisation>
            </certificate>
            <package price="1000" packType="packType1">
                <count cnt="150" measureUnit="milliliter"/>
            </package>
            <dosage dosageCount="2" dosageMeasureUnit="milliliter" times="3" per="30m" for="adult men"/>
            <dosage dosageCount="5" dosageMeasureUnit="gram" times="6" per="day" for="pregnant"/>
        </versions>
        <versions>
            <certificate certificateID="fdsf">
                <startDate>1995-05-11</startDate>
                <endDate>1995-05-11</endDate>
                <registeringOrganisation>sdfsf</registeringOrganisation>
            </certificate>
            <representationTypes>
                <type>pills</type>
                <type>drops</type>
            </representationTypes>
            <package price="" packType="">
                <count cnt=""/>
            </package>
            <dosage dosageCount="" per="" for=""/>
        </versions>
    </medicine>

    <medicine name="name1" ID="ae3">
        <pharm>s</pharm>
        <group>antibiotics</group>
        <versions>
            <certificate certificateID="sad1">
                <startDate>1995-05-11</startDate>
                <endDate>2016-11-11</endDate>
                <registeringOrganisation>organization1</registeringOrganisation>
            </certificate>
            <package price="1000" packType="">
                <count cnt="150" measureUnit="milliliter"/>
            </package>
            <dosage dosageCount="2" dosageMeasureUnit="milliliter" times="3" per="30m" for="adult men"/>
            <dosage dosageCount="5" dosageMeasureUnit="gram" times="6" per="day" for="pregnant"/>
        </versions>
    </medicine>

    <medicine name="name1" ID="ae4">
        <pharm>s</pharm>
        <group>antibiotics</group>
        <analogues>
            <analogueID>ae3</analogueID>
            <analogueID>ae2</analogueID>
        </analogues>
        <versions>
            <certificate certificateID="ads2">
                <startDate>1995-05-11</startDate>
                <endDate>2016-11-11</endDate>
                <registeringOrganisation>organization1</registeringOrganisation>
            </certificate>
            <package price="1000" packType="packType1">
                <count cnt="150" measureUnit="milliliter"/>
            </package>
            <dosage dosageCount="2" dosageMeasureUnit="milliliter" times="3" per="30m" for="adult men"/>
            <dosage dosageCount="5" dosageMeasureUnit="gram" times="6" per="day" for="pregnant"/>
        </versions>
    </medicine>

</medicines>
